function tutorial_connectivity(reports_dir)
% TUTORIAL_CONNECTIVITY: Script that runs the Brainstorm connectivity tutorial.
%
% INPUTS: 
%    - reports_dir  : Directory where to save the execution report (instead of displaying it)

% @=============================================================================
% This function is part of the Brainstorm software:
% https://neuroimage.usc.edu/brainstorm
% 
% Copyright (c) University of Southern California & McGill University
% This software is distributed under the terms of the GNU General Public License
% as published by the Free Software Foundation. Further details on the GPLv3
% license can be found at http://www.gnu.org/copyleft/gpl.html.
% 
% FOR RESEARCH PURPOSES ONLY. THE SOFTWARE IS PROVIDED "AS IS," AND THE
% UNIVERSITY OF SOUTHERN CALIFORNIA AND ITS COLLABORATORS DO NOT MAKE ANY
% WARRANTY, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO WARRANTIES OF
% MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE, NOR DO THEY ASSUME ANY
% LIABILITY OR RESPONSIBILITY FOR THE USE OF THIS SOFTWARE.
%
% For more information type "brainstorm license" at command prompt.
% =============================================================================@
%
% Author: Raymundo Cassani, 2021-2022
%         Francois Tadel, 2022


%% ===== PARAMETERS =====
% Output folder for reports
if (nargin < 1) || isempty(reports_dir) || ~isfolder(reports_dir)
    reports_dir = [];
end


%% ===== CREATE PROTOCOL  =====
% Start brainstorm without the GUI
if ~brainstorm('status')
    brainstorm nogui
end
% Create Protocol
ProtocolName = 'TutorialConnectivity';
% Delete existing protocol
gui_brainstorm('DeleteProtocol', ProtocolName);
% Create new protocol
gui_brainstorm('CreateProtocol', ProtocolName, 0, 0);


%% ===== SIMULATE DATA (MVAR MODEL) =====
% Seed for random number generator
rng(111); 
% Process: Simulate AR signals
sFileSim = bst_process('CallProcess', 'process_simulate_ar_spectra', [], [], ...
    'subjectname',  'Subject01', ...
    'condition',    'Simulation', ...
    'samples',      12000, ...
    'srate',        120, ...
    'interactions', ['1, 1 / 10, 25 / 0.3, 0.5' 10 ...
                     '2, 2 / 10, 25 / 0.7, 0.3' 10 ... 
                     '3, 3 / 10, 25 / 0.2, 0.2' 10 ... 
                     '1, 3 / 25 / 0.1']);

% Make sure the display mode is "columns"
bst_set('TSDisplayMode', 'column');
% Process: Snapshot: Recordings time series
bst_process('CallProcess', 'process_snapshot', sFileSim, [], ...
    'type',    'data', ...  % Recordings time series
    'Comment', 'Simulated signals');

                 

%% ===== CORRELATION =====
% Process: Correlation NxN
sFiles = bst_process('CallProcess', 'process_corr1n', sFileSim, [], ...
    'timewindow', [], ...
    'scalarprod', 0, ...
    'outputmode', 1);  % Save individual results (one file per input file)

% Process: Snapshot: Connectivity matrix
bst_process('CallProcess', 'process_snapshot', sFiles, [], ...
    'type',    'connectimage', ...  % Connectivity matrix
    'Comment', 'Correlation NxN');


%% ===== COHERENCE =====
% Magnitude squared coherence (MSC)
% Process: Coherence NxN [2021]
sFiles = bst_process('CallProcess', 'process_cohere1n_2021', sFileSim, [], ...
    'timewindow',   [], ...
    'removeevoked', 0, ...
    'cohmeasure',   'mscohere', ...  % Magnitude-squared Coherence|C|^2 = |Gxy|^2/(Gxx*Gyy)
    'win_length',   1, ...
    'overlap',      50, ...
    'maxfreq',      60, ...
    'outputmode',   'input');  % Save individual results (one output file per input file)

% Process: Snapshot: Frequency spectrum
bst_process('CallProcess', 'process_snapshot', sFiles, [], ...
    'type',    'spectrum', ...  % Frequency spectrum
    'Comment', 'MSC NxN');

% Process: Snapshot: Connectivity graph
bst_process('CallProcess', 'process_snapshot', sFiles, [], ...
    'type',    'connectgraph', ...  % Connectivity graph
    'Comment', 'MSC NxN');

% Process: Snapshot: Connectivity matrix
bst_process('CallProcess', 'process_snapshot', sFiles, [], ...
    'type',    'connectimage', ...  % Connectivity matrix
    'Comment', 'MSC NxN');

% Imaginary coherence (IC)
% Process: Coherence NxN [2021]
sFiles = bst_process('CallProcess', 'process_cohere1n_2021', sFileSim, [], ...
    'timewindow',   [], ...
    'removeevoked', 0, ...
    'cohmeasure',   'icohere2019', ...  % Imaginary Coherence (2019)IC    = |imag(C)|
    'win_length',   1, ...
    'overlap',      50, ...
    'maxfreq',      60, ...
    'outputmode',   'input');  % Save individual results (one output file per input file)

% Process: Snapshot: Frequency spectrum
bst_process('CallProcess', 'process_snapshot', sFiles, [], ...
    'type',    'spectrum', ...  % Frequency spectrum
    'Comment', 'Imaginary coherence NxN');

% Lagged coherence (LC)
% Process: Coherence NxN [2021]
sFiles = bst_process('CallProcess', 'process_cohere1n_2021', sFileSim, [], ...
    'timewindow',   [], ...
    'removeevoked', 0, ...
    'cohmeasure',   'lcohere2019', ...  % Lagged Coherence (2019)LC    = |imag(C)|/sqrt(1-real(C)^2)
    'win_length',   1, ...
    'overlap',      50, ...
    'maxfreq',      60, ...
    'outputmode',   'input');  % Save individual results (one output file per input file)

% Process: Snapshot: Frequency spectrum
bst_process('CallProcess', 'process_snapshot', sFiles, [], ...
    'type',    'spectrum', ...  % Frequency spectrum
    'Comment', 'Lagged coherence NxN');


%% ===== GRANGER CAUSALITY =====
% Process: Bivariate Granger causality NxN
sFiles = bst_process('CallProcess', 'process_granger1n', sFileSim, [], ...
    'timewindow',   [], ...
    'removeevoked', 0, ...
    'grangerorder', 6, ...
    'outputmode',   1);  % Save individual results (one file per input file)

% Process: Snapshot: Connectivity graph
bst_process('CallProcess', 'process_snapshot', sFiles, [], ...
    'type',    'connectgraph', ...  % Connectivity graph
    'Comment', 'Granger causality NxN');

% Process: Snapshot: Connectivity matrix
bst_process('CallProcess', 'process_snapshot', sFiles, [], ...
    'type',    'connectimage', ...  % Connectivity matrix
    'Comment', 'Granger causality NxN');


%% ===== SPECTRAL GRANGER CAUSALITY =====
% Process: Bivariate Granger causality (spectral) NxN
sFiles = bst_process('CallProcess', 'process_spgranger1n', sFileSim, [], ...
    'timewindow',   [], ...
    'removeevoked', 0, ...
    'grangerorder', 6, ...
    'maxfreqres',   1, ...
    'maxfreq',      60, ...
    'outputmode',   1);  % Save individual results (one file per input file)

% Process: Snapshot: Frequency spectrum
bst_process('CallProcess', 'process_snapshot', sFiles, [], ...
    'type',    'spectrum', ...  % Frequency spectrum
    'Comment', 'Spectral Granger causality NxN');


%% ===== ENVELOPE CORRELATION =====
% Process: Envelope Correlation NxN (2020)
% Hilbert transform
sFiles = bst_process('CallProcess', 'process_henv1n', sFileSim, [], ...
    'timewindow',   [], ...
    'removeevoked', 0, ...
    'tfmeasure',    'hilbert', ...  % Hilbert transform
    'edit',         struct(...
         'Comment',         'Complex', ...
         'TimeBands',       [], ...
         'Freqs',           {{'delta', '2, 4', 'mean'; 'theta', '5, 7', 'mean'; 'alpha', '8, 12', 'mean'; 'beta', '15, 29', 'mean'; 'gamma1', '30, 59', 'mean'}}, ...
         'ClusterFuncTime', 'none', ...
         'Measure',         'none', ...
         'Output',          'all', ...
         'SaveKernel',      0), ...
    'tfsplit',      1, ...
    'cohmeasure',   'oenv', ...  % Envelope correlation (orthogonalized) 
    'statdyn',      'dynamic', ...  % Dynamic
    'win_length',   5, ...
    'win_overlap',  50, ...
    'parallel',     0, ...
    'outputmode',   1);  % Save individual results (one file per input file)

% Process: Snapshot: Frequency spectrum
bst_process('CallProcess', 'process_snapshot', sFiles, [], ...
    'type',    'spectrum', ...  % Frequency spectrum
    'Comment', 'Envelope correlation (Hilbert transform) NxN');

% Process: Envelope Correlation NxN (2020)
% Morlet wavelet
sFiles = bst_process('CallProcess', 'process_henv1n', sFileSim, [], ...
    'timewindow',   [], ...
    'removeevoked', 0, ...
    'tfmeasure',    'morlet', ...  % Morlet wavelet
    'edit',         struct(...
         'Comment',         'Complex,1-60Hz', ...
         'TimeBands',       [], ...
         'Freqs',           [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60], ...
         'MorletFc',        1, ...
         'MorletFwhmTc',    3, ...
         'ClusterFuncTime', 'none', ...
         'Measure',         'none', ...
         'Output',          'all', ...
         'SaveKernel',      0), ...
    'tfsplit',      1, ...
    'cohmeasure',   'oenv', ...  % Envelope correlation (orthogonalized) 
    'statdyn',      'dynamic', ...  % Dynamic
    'win_length',   5, ...
    'win_overlap',  50, ...
    'parallel',     0, ...
    'outputmode',   1);  % Save individual results (one file per input file)

% Process: Snapshot: Frequency spectrum
bst_process('CallProcess', 'process_snapshot', sFiles, [], ...
    'type',    'spectrum', ...  % Frequency spectrum
    'Comment', 'Envelope correlation (Morlet wavelet) NxN');


%% ===== PHASE LOCKING VALUE =====
% Process: PLV: Phase locking value
sFiles = bst_process('CallProcess', 'process_plv1n', sFileSim, [], ...
    'timewindow', [], ...
    'freqbands',  {'delta', '2, 4', 'mean'; 'theta', '5, 7', 'mean'; 'alpha', '8, 12', 'mean'; 'beta', '15, 29', 'mean'; 'gamma1', '30, 59', 'mean'}, ...
    'plvmethod',  'plv', ...  % PLV: Phase locking value
    'keeptime',   0, ...
    'plvmeasure', 2, ...  % Magnitude
    'outputmode', 1);  % Save individual results (one file per input file)

% Process: Snapshot: Frequency spectrum
bst_process('CallProcess', 'process_snapshot', sFiles, [], ...
    'type',    'spectrum', ...  % Frequency spectrum
    'Comment',  'Phase locking value NxN');


%% ===== PHASE TRANSFER ENTROPY =====
% Process: Phase Transfer Entropy NxN
sFiles = bst_process('CallProcess', 'process_pte1n', sFileSim, [], ...
    'timewindow', [], ...
    'freqbands',  {'delta', '2, 4', 'mean'; 'theta', '5, 7', 'mean'; 'alpha', '8, 12', 'mean'; 'beta', '15, 29', 'mean'; 'gamma1', '30, 59', 'mean'}, ...
    'normalized', 0, ...
    'outputmode', 1);  % Save individual results (one file per input file)

% Process: Snapshot: Frequency spectrum
bst_process('CallProcess', 'process_snapshot', sFiles, [], ...
    'type',    'spectrum', ...  % Frequency spectrum
    'Comment', 'Phase transfer entropy NxN');


%% ===== SAVE REPORT =====
% Save and display report
ReportFile = bst_report('Save', []);
if ~isempty(reports_dir) && ~isempty(ReportFile)
    bst_report('Export', ReportFile, reports_dir);
else
    bst_report('Open', ReportFile);
end